server:
  port: 8084
spring:
  redis:
    host: localhost
    password: 123456
  application:
    name: xiaoyu-eureka-server
eureka:
  instance:
    ##注册中心IP地址
    hostname: 127.0.0.1
  client:
    service-url:
      ##注册地址
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/
      ##是否需要注册到注册中心
    register-with-eureka: true
    ##是否需要检索服务信息
    fetch-registry: true